version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=LesBonsPlans
      - MYSQL_USER=LBP-admin
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

  mariadb2:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=LesBonsPlansApp
      - MYSQL_USER=LBP
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data2:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mariadb_data:
  mariadb_data2:

networks:
  mynetwork:
